config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :users
  resources :posts do
    collection do
      get 'list'
    end
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  attachment :profile_image
  validates :username, presence: true

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource) 
    posts_path(resource)
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      render :index
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

  def new
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "guest"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    @like.save
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) DESC').limit(9).pluck(:post_id))
    # @users = User.all.order(id: "DESC").limit(10)
    @users = User.find(Post.group(:user_id).order('count(user_id) DESC').limit(10).pluck(:user_id))
  end

  def list
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(9)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "記事を投稿しました。"
    else
      render :new
    end
  end

  def edit
    if @post.user != current_user
        redirect_to posts_path, alert: "不正なアクセスです。"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(post.user), notice: "投稿を削除しました。"
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image, :comment, :post_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.order("created_at DESC").page(params[:page]).per(8)
  end

  def show
  end

  def edit
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment], remote: true do |f| %>
  <div class="field">
    <div class="control">
      <%= f.text_area :content, class:"input", placeholder:"コメント" %>
      <%= f.hidden_field :post_id, value: @post.id %>
    </div>
  </div>
  <br>
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit 'コメントする', class:"button is-link form__submit" %>
    </div>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |c| %>
  <div>
    <a href="/users/<%= c.user.id %>"><%= c.user.username %></a>
    <%= c.content %>
    <% if c.user.id == current_user.id %>
      <br>
      投稿日：<%= c.created_at.to_s(:datetime_jp) %>
        <%= link_to post_comment_path(c.post_id, c.id), method: :delete, remote: true, data: {confirm: "削除しますか？"} do %>
          <span class="panel-icon">
            <i class="fas fa-trash"></i>
          </span>
        <% end %>
      <hr>
    <% else %>
      <br>
        投稿日：<%= c.created_at.to_s(:datetime_jp) %>
      <hr>
    <% end %>
  </div>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments.order(created_at: :desc) }) %>")
$("textarea").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>イクメン クエスト</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <section class="hero is-success">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <header class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <%= link_to root_path, class: "navbar-item" do %>
              <h1 class="title is-4" >イクメン クエスト</h1>
            <% end %>
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroC" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to "投稿一覧", list_posts_path, class: "button is-success is-inverted" %>
            </span>
            <span class="navbar-item">
              <%= link_to "イクメン一覧", users_path, class: "button is-success is-inverted" %>
            </span>
            <% if user_signed_in? %>
            <p class="navbar-item">
              <%= link_to user_path(current_user), class: "button is-success is-inverted" do %>
                <%= "#{current_user.username} のページ" %>
                <%= attachment_image_tag current_user, :profile_image, :fill, 70, 70, fallback: "no-image.png" %>
              <% end %>
            </p>
            <span class="navbar-item">
              <%= link_to "新規投稿", new_post_path %>
            </span>
            <span class="navbar-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </span>
            <% else %>
              <span class="navbar-item">
                <%= link_to 'ゲストログイン（閲覧用）', homes_guest_sign_in_path, method: :post %>
              </span>
              <span class="navbar-item">
                <%= link_to "ログイン", new_user_session_path %>
              </span>
              <span class="navbar-item">
                <%= link_to "新規登録", new_user_registration_path %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </header>
  </div>
  </section>      
    <%= yield %>
  <footer class="footer">
  <div class="content has-text-centered">
      <%= image_tag("image01.jpg", size: '100x150') %>
      <%= image_tag("rpg.png", size: '200x150') %>
      <%= image_tag("boss.png", size: '200x150') %>
    <p>
      <strong>Ikumen Quest</strong> by <a href="https://makunblog.com">Masahide Danjyo</a>.
Check this GitHub source code<a href="https://github.com/john03191">Git Hub mypage</a>
    </p>
    <hr>
  </div>
</footer>
  </body>
</html>

app/views/likes/_like.html.erb
<% if current_user.already_liked?(post) %>
  <%= button_to post_like_path(post, post.id), method: :delete, remote: true do %>
    <span class="icon has-text-danger"><i class="fas fa-2x fa-heart"></i></span>
  <% end %>
<% else %>
  <%= button_to post_likes_path(post), method: :post, remote: true do %>
    <i class="far fa-2x fa-heart"></i>
  <% end %>
<% end %>
<div class="like_font"><%= post.likes.count %></div>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿内容の編集
      </h1>
    </div>
  </div>
</section>

<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @post do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        トップページ
      </h1>
    </div>
  </div>
</section>

<div class="hero-body">
  <div class="columns">
    <div class="column is-3">
      <i class="fas fa-crown">投稿数ランキング</i>
    <div class="card">
      <% @users.each do |user| %>
      <div class="user_rank">
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <%= attachment_image_tag user, :profile_image, :fill, 200, 200, fallback: "no-image.png" %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong><%= user.username %></strong> <small><%= user.email %></small>
                <br>
                投稿数: <%= user.posts.count %>
              </p>
            </div>
            <nav class="level is-mobile">
              </div>
            </nav>
          </div>
          <% end %>
        </article>
      </div>
    </div>
    <div class="column">
      <i class="fas fa-crown posts__like__rank">いいね数ランキング</i>
      <section class="section posts__card">
        <div class="container">
          <div class="columns is-multiline">
            <% @all_ranks.each do |post| %>
              <div class="column is-4">
                <div class="card">
                  <div class="card-image">
                    <figure class="image is-4by3">
                      <%= link_to post_path(post) do %>
                        <%= attachment_image_tag post, :image %>
                      <% end %>
                    </figure>
                  </div>
                  <div class="card-content">
                    <div class="media">
                      <div class="media-left">
                        <figure class="image is-48x48">
                          <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                        </figure>
                      </div>
                      <div class="media-content">
                        <div class="title"><%=link_to post.user.username, user_path(post.user) %></div>
                      </div>
                    </div>

                    <div class="content">
                      <p class="title is-4"><%= post.title %></p>
                    </div>
                    <div class="content">
                      <p class="title is-4">いいね：<%= post.likes.count %></p>
                    </div>
                    <div class="content">
                      <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
        

app/views/posts/list.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿一覧
      </h1>
    </div>
  </div>
</section>

<div class="hero-body">
    <div class="column">
      <section class="section">
        <div class="container">
          <div class="columns is-multiline">
            <% @posts.each do |post| %>
              <div class="column is-4">
                <div class="card">
                  <div class="card-image">
                    <figure class="image is-4by3">
                      <%= link_to post_path(post) do %>
                        <%= attachment_image_tag post, :image %>
                      <% end %>
                    </figure>
                  </div>
                  <div class="card-content">
                    <div class="media">
                      <div class="media-left">
                        <figure class="image is-48x48">
                          <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                        </figure>
                      </div>
                      <div class="media-content">
                        <div class="title"><%=link_to post.user.username, user_path(post.user) %></div>
                      </div>
                    </div>

                    <div class="content">
                      <p class="title is-4"><%= post.title %></p>
                    </div>
                    <div class="content">
                      <p class="title is-4">いいね：<%= post.likes.count %></p>
                    </div>
                    <div class="content">
                      <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<div class="hero-body">  
  <%= paginate(@posts) %>
</div>
        

app/views/posts/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規投稿
      </h1>
    </div>
  </div>
</section>


<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @post do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @post, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4">タイトル：<%= @post.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>内容</th>
                </tr>
                <tr>
                  <td><%= simple_format @post.body %></td>
                </tr>
                <tr>
                  <td class="display-flex">
                    <div id="likes_buttons_<%= @post.id %>">
                      <%= render partial: 'likes/like', locals: { post: @post} %>
                    </div>
                  </td>
                </tr>
              </table>
              <% if @post.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_post_path(@post), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            <%= @post.user.username %>さん
          </p>
          <div class="panel-block">
            <p class="control">
              一言：<%= @post.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@post.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @post.user.username %> さんのページへ
          <% end %>
        </article>
        <h2>コメント一覧</h2>
        <div class="comments_index">
          <div id='comments_area'>
            <%= render partial: 'comments/index', locals: { comments: @comments } %>
          </div>
        </div>
        <% if user_signed_in? %>
          <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
        <% end %>
        
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <% if @user.id == 1 %>
          <p>ゲストユーザーの編集はできません。</p>
          <%= link_to "戻る", root_path, class: "button is-success is-inverted" %>
          <% else %>
          <%= form_for @user do |f| %>
            <div class="field">
              <%= f.label :username, "ユーザー名", class: "label" %>
              <%= f.text_field :username, class: "input" %>
            </div>

            <div class="field">
              <%= f.label :email, "メールアドレス", class: "label" %>
              <%= f.email_field :email, class: "input" %>
            </div>

            <div class="field">
              <%= f.label :profile, "プロフィール", class: "label" %>
              <%= f.text_area :profile, class: "textarea" %>
            </div>

            <div class="field">
              <%= f.label :profile_image, "プロフィール画像", class: "label" %>
                <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback: "no-image.png" %>
              <%= f.attachment_field :profile_image, class: "input image_form__contents__field hidden_file" %>
            </div>

            <%= f.submit "更新", class: "button is-success" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        イクメン一覧
      </h3>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 200, 200, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.posts.count %>
              </div>
              <div class="content">
                いいね数：
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<div class="hero-body">  
  <%= paginate(@users) %>
</div>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                  <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.posts.each do |post| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag post, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to post_path(post), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    詳細をみる
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_post_path(post), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      編集をする
                    <% end %>
                    <%= link_to post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>